version: "3"

services:

  payment-service:
    image: kinecosystem/payment-service
    volumes:
      - .:/opt/app
    ports:
      - 3000
    links:
      - redis
    environment:
      &app_env_vars
      APP_DEBUG: 'True'
      APP_PORT: 3000
      APP_HOST: '0.0.0.0'
      APP_NAME: 'payment-service'
      APP_REDIS: redis://redis:6379/0
      CHANNEL_SALT: some_salt
      STELLAR_BASE_SEED: ${STELLAR_BASE_SEED}
      STELLAR_ADDRESS: ${STELLAR_ADDRESS}
      STELLAR_HORIZON_URL: ${STELLAR_HORIZON_URL}
      STELLAR_NETWORK: ${STELLAR_NETWORK}
      STELLAR_KIN_ISSUER_ADDRESS: ${STELLAR_KIN_ISSUER_ADDRESS}
      STELLAR_KIN_TOKEN_NAME: ${STELLAR_KIN_TOKEN_NAME}
      STELLAR_INITIAL_XLM_AMOUNT: ${STELLAR_INITIAL_XLM_AMOUNT}

  payment-worker:
    image: kinecosystem/payment-service
    volumes:
      - .:/opt/app
    command: pipenv run python worker.py
    links:
      - redis
    environment:
      <<: *app_env_vars

  payment-watcher:
    image: kinecosystem/payment-service
    volumes:
      - .:/opt/app
    command: pipenv run python watcher.py
    links:
      - redis
    environment:
      <<: *app_env_vars

  redis:
    image: redis
    ports:
      - 6379
