export \
    STELLAR_HORIZON_URL='http://horizon-ecosystem-c5dc-298387387.us-east-1.elb.amazonaws.com' \
    STELLAR_NETWORK='Public Global Kin Ecosystem Network ; June 2018' \
    STELLAR_KIN_ISSUER_ADDRESS='GDF42M3IPERQCBLWFEZKQRK77JQ65SCKTU3CW36HZVCX7XX5A5QXZIVK' \
    STELLAR_KIN_TOKEN_NAME='KIN' \
    STELLAR_INITIAL_XLM_AMOUNT=2
